on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build + Push Vendure Docker Image + Trigger Dokploy Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Extract metadata
      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push prod image
      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: ./vendure
          file: ./vendure/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dokploy-vendure-demo:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dokploy-vendure-demo:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Trigger Dokploy deployment webhook
      - name: Trigger Dokploy deployment for Vendure API
        run: |
          curl -f -X POST "${{ secrets.DEPLOY_WEBHOOK_VENDURE_API }}"

      # Trigger Dokploy deployment webhook
      - name: Trigger Dokploy deployment for Vendure Worker
        run: |
          curl -f -X POST "${{ secrets.DEPLOY_WEBHOOK_VENDURE_WORKER }}"